language: objective-c
matrix:
  include:
  - osx_image: xcode10
    env: PUBLISH_NUGET=yes
  - osx_image: xcode9.4
  - osx_image: xcode9.3
  - osx_image: xcode9.2
  - osx_image: xcode9.1
  - osx_image: xcode9

cache:
  directories:
  - Carthage
  - Inspector/node_modules

install:
  - wget https://download.microsoft.com/download/D/0/4/D04C5489-278D-4C11-9BD3-6128472A7626/dotnet-sdk-2.1.301-osx-x64.pkg -O ~/dotnet-sdk-2.1.301-osx-gs-x64.pkg
  - sudo installer -pkg ~/dotnet-sdk-2.1.301-osx-gs-x64.pkg -target /
  - PATH="/usr/local/share/dotnet/:$PATH"
  - dotnet --version

script:
  - ./Scripts/bootstrap.sh
  - ./signing/add-key.sh
  - security find-identity -v -p codesigning
  - ./build-ipa.sh
  - cd Quamotion.WebDriverAgent
  - cp ../out/WebDriverAgent-$TRAVIS_BUILD_NUMBER.zip ./WebDriverAgent.zip
  - dotnet build -c Release /p:VersionSuffix=r$TRAVIS_BUILD_NUMBER-$osx_image
  - dotnet pack -c Release /p:VersionSuffix=r$TRAVIS_BUILD_NUMBER-$osx_image
#  - dotnet nuget push bin/Release/Quamotion.WebDriverAgent.1.0.0-r$TRAVIS_BUILD_NUMBER-$osx_image.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_TOKEN
